/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.HoaDonDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.DichVuDaSuDung;
import model.HoaDon;
import model.LinhKien;
import model.LinhKienDaSuDung;
import model.NhanVien;
import model.Xe;
import model.XeTrongHoaDon;

/**
 *
 * @author tuann
 */
public class TimKiemHoaDonFrm extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TimKiemHoaDon
     */
    private NhanVien nhanVien;
    private HoaDon hoaDon;
    private ArrayList<XeTrongHoaDon> listXeTrongHoaDon;
    private ArrayList<DichVuDaSuDung> listDichVuDaSuDung;
    private ArrayList<LinhKienDaSuDung> listLinhKienDaSuDung;

    public TimKiemHoaDonFrm(NhanVien nv) {
        initComponents();
        this.nhanVien = nv;
        btnTimKiem.addActionListener(this);
        btnXacNhan.addActionListener(((e) -> {
            (new XacNhanFrm(nv, hoaDon)).setVisible(true);
            this.dispose();
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXe = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLinhKien = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Tim Kiem Hoa Don");

        jLabel2.setText("Ma Hoa Don");

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnTimKiem.setText("Tim Kiem");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Xe");

        tblXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bien Xe", "Hang Xe", "Loai Xe"
            }
        ));
        jScrollPane1.setViewportView(tblXe);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Dich Vu Da Dung");

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Ten", "Don gia", "So luong", "Thanh Tien"
            }
        ));
        jScrollPane2.setViewportView(tblDichVu);

        tblLinhKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Ten", "Don gia", "So luong", "Thanh Tien"
            }
        ));
        jScrollPane3.setViewportView(tblLinhKien);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Linh Kien Da Dung");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tong Tien:");

        btnXacNhan.setText("Xac Nhan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnXacNhan)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane3)))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXacNhan)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblLinhKien;
    private javax.swing.JTable tblXe;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        hoaDon = new HoaDon();
        HoaDonDAO hoaDonDAO = new HoaDonDAO();
        hoaDon = hoaDonDAO.searchHoaDon(Integer.parseInt(txtTimKiem.getText()));
        listXeTrongHoaDon = hoaDon.getListXeTrongHoaDon();
        listDichVuDaSuDung = new ArrayList<>();
        listLinhKienDaSuDung = new ArrayList<>();
        for (int i = 0; i < listXeTrongHoaDon.size(); i++) {
                //System.out.println(listXeTrongHoaDon.get(i).getListDichVuDaSuDung().size());
            for (int j = 0; j < listXeTrongHoaDon.get(i).getListDichVuDaSuDung().size(); j++) {
                listDichVuDaSuDung.add(listXeTrongHoaDon.get(i).getListDichVuDaSuDung().get(j));
            }
            for (int j = 0; j < listXeTrongHoaDon.get(i).getListLinhKienDaSuDung().size(); j++) {
                listLinhKienDaSuDung.add(listXeTrongHoaDon.get(i).getListLinhKienDaSuDung().get(j));
            }
        }

        String data1[][] = new String[listXeTrongHoaDon.size()][3];
        for (int i = 0; i < listXeTrongHoaDon.size(); i++) {
            Xe xe = listXeTrongHoaDon.get(i).getXe();
            data1[i][0] = xe.getBienSo();
            data1[i][1] = xe.getHangXe();
            data1[i][2] = xe.getLoaiXe();
        }
        String[] columnNames1 = {"Bien xe", "Hang xe", "Loai xe"};
        DefaultTableModel dtm1 = new DefaultTableModel(data1, columnNames1);
        tblXe.setModel(dtm1);
      
        String data2[][] = new String[listDichVuDaSuDung.size()][5];
        for (int i = 0; i < listDichVuDaSuDung.size(); i++) {
            DichVu dichVu = listDichVuDaSuDung.get(i).getDichVu();
            data2[i][0] = (i + 1) + "";
            data2[i][1] = dichVu.getTen();
            data2[i][2] = listDichVuDaSuDung.get(i).getGia() + "";
            data2[i][3] = listDichVuDaSuDung.get(i).getSoluong() + "";
            data2[i][4] = listDichVuDaSuDung.get(i).getThanhtien() + "";
        }

        String[] columnNames2 = {"TT", "Ten", "Don gia", "So Luong", "Thanh Tien"};
        DefaultTableModel dtm2 = new DefaultTableModel(data2, columnNames2);
        tblDichVu.setModel(dtm2);
        
        String data3[][] = new String[listLinhKienDaSuDung.size()][5];
        for (int i = 0; i < listLinhKienDaSuDung.size(); i++) {
            LinhKien linhKien = listLinhKienDaSuDung.get(i).getLinhKien();
            data3[i][0] = (i + 1) + "";
            data3[i][1] = linhKien.getTen();
            data3[i][2] = listLinhKienDaSuDung.get(i).getGia() + "";
            data3[i][3] = listLinhKienDaSuDung.get(i).getSoLuong() + "";
            data3[i][4] = listLinhKienDaSuDung.get(i).getThanhTien() + "";
        }

        String[] columnNames3 = {"TT", "Ten", "Don gia", "So Luong", "Thanh Tien"};
        DefaultTableModel dtm3 = new DefaultTableModel(data3, columnNames3);
        tblLinhKien.setModel(dtm3);
        
        txtTongTien.setText(hoaDon.getTinhTien()+"");
    }
}
